// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: email/v1/email.proto

package emailv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/paladignus/actajus/proto/email/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// EmailServiceName is the fully-qualified name of the EmailService service.
	EmailServiceName = "email.v1.EmailService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EmailServiceCreateEmailProcedure is the fully-qualified name of the EmailService's CreateEmail
	// RPC.
	EmailServiceCreateEmailProcedure = "/email.v1.EmailService/CreateEmail"
	// EmailServiceUpdateEmailProcedure is the fully-qualified name of the EmailService's UpdateEmail
	// RPC.
	EmailServiceUpdateEmailProcedure = "/email.v1.EmailService/UpdateEmail"
)

// EmailServiceClient is a client for the email.v1.EmailService service.
type EmailServiceClient interface {
	CreateEmail(context.Context, *connect.Request[v1.CreateEmailRequest]) (*connect.Response[v1.CreateEmailResponse], error)
	UpdateEmail(context.Context, *connect.Request[v1.UpdateEmailRequest]) (*connect.Response[v1.UpdateEmailResponse], error)
}

// NewEmailServiceClient constructs a client for the email.v1.EmailService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEmailServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EmailServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &emailServiceClient{
		createEmail: connect.NewClient[v1.CreateEmailRequest, v1.CreateEmailResponse](
			httpClient,
			baseURL+EmailServiceCreateEmailProcedure,
			opts...,
		),
		updateEmail: connect.NewClient[v1.UpdateEmailRequest, v1.UpdateEmailResponse](
			httpClient,
			baseURL+EmailServiceUpdateEmailProcedure,
			opts...,
		),
	}
}

// emailServiceClient implements EmailServiceClient.
type emailServiceClient struct {
	createEmail *connect.Client[v1.CreateEmailRequest, v1.CreateEmailResponse]
	updateEmail *connect.Client[v1.UpdateEmailRequest, v1.UpdateEmailResponse]
}

// CreateEmail calls email.v1.EmailService.CreateEmail.
func (c *emailServiceClient) CreateEmail(ctx context.Context, req *connect.Request[v1.CreateEmailRequest]) (*connect.Response[v1.CreateEmailResponse], error) {
	return c.createEmail.CallUnary(ctx, req)
}

// UpdateEmail calls email.v1.EmailService.UpdateEmail.
func (c *emailServiceClient) UpdateEmail(ctx context.Context, req *connect.Request[v1.UpdateEmailRequest]) (*connect.Response[v1.UpdateEmailResponse], error) {
	return c.updateEmail.CallUnary(ctx, req)
}

// EmailServiceHandler is an implementation of the email.v1.EmailService service.
type EmailServiceHandler interface {
	CreateEmail(context.Context, *connect.Request[v1.CreateEmailRequest]) (*connect.Response[v1.CreateEmailResponse], error)
	UpdateEmail(context.Context, *connect.Request[v1.UpdateEmailRequest]) (*connect.Response[v1.UpdateEmailResponse], error)
}

// NewEmailServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEmailServiceHandler(svc EmailServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	emailServiceCreateEmailHandler := connect.NewUnaryHandler(
		EmailServiceCreateEmailProcedure,
		svc.CreateEmail,
		opts...,
	)
	emailServiceUpdateEmailHandler := connect.NewUnaryHandler(
		EmailServiceUpdateEmailProcedure,
		svc.UpdateEmail,
		opts...,
	)
	return "/email.v1.EmailService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EmailServiceCreateEmailProcedure:
			emailServiceCreateEmailHandler.ServeHTTP(w, r)
		case EmailServiceUpdateEmailProcedure:
			emailServiceUpdateEmailHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEmailServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEmailServiceHandler struct{}

func (UnimplementedEmailServiceHandler) CreateEmail(context.Context, *connect.Request[v1.CreateEmailRequest]) (*connect.Response[v1.CreateEmailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("email.v1.EmailService.CreateEmail is not implemented"))
}

func (UnimplementedEmailServiceHandler) UpdateEmail(context.Context, *connect.Request[v1.UpdateEmailRequest]) (*connect.Response[v1.UpdateEmailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("email.v1.EmailService.UpdateEmail is not implemented"))
}
