POST http://localhost:8080/signin
content-type: application/json

{
    "cpf": "11144477735",
    "password": "admin123"
}

###
POST http://localhost:8080/auth/email
content-type: application/json

{
    "cpf": "11144477735"
}

###
POST http://localhost:8080/auth/recover
content-type: application/json

{
    "email": "marcelo@marcelo.eti.br"
}

###
POST http://localhost:8080/auth/renew
content-type: application/json

{
    "cpf": "111.444.777-35",
    "password": "!Admin123",
    "token": "tVtTlI5wXXcdrGpXhmis_75kfKxW1EkjJE6ggdBnUws="
}

###
GET http://localhost:8080/companies
content-type: application/json

###
POST http://localhost:8080/companies/find/id
content-type: application/json

{
    "id": 2
}

###
POST http://localhost:8080/companies/find/cnpj
content-type: application/json

{
    "cnpj": "48.922.852/0001-62"
}

# "cnpj": "03.015.475/0001-40"

###
POST http://localhost:8080/companies
content-type: application/json

{
    "registered_by": 3,
    "name": "Actajus",
    "trade_name": "Actajus Sistema Jurídico",
    "cnpj": "48.922.852/0001-62",
    "address": {
        "zip": "12345-678",
        "title": "Avenida",
        "street": "Paulista",
        "complement": "Apartamento 123",
        "reference": "Perto da escola Izabel",
        "number": 123,
        "neighborhood": "Centro",
        "city": "São Paulo",
        "state": "São Paulo",
        "country": "Brasil"
    },
    "phone": {
        "number": "+5567912345678",
        "kind": "Celular",
        "department": "Comercial"
    },
    "email": {
        "address": "falecosm2@acatajus.com.br"
    },
    "social_media": [
        {
            "platform": "facebook",
            "url": "https://www.facebook.com/asctajus2"
        },
        {
            "platform": "Linkedin",
            "url": "https://www.linkedin.com/in/actajsus2/"
        },
        {
            "platform": "Instagram",
            "url": "https://www.instagram.com/actajsus2/"
        },
        {
            "platform": "X",
            "url": "https://x.com/actajuss2"
        },
        {
            "platform": "Site",
            "url": "https://twitter.com/actasjus2"
        }
    ]
}


###
PUT  http://localhost:8080/companies
content-type: application/json

{
    "id_company": 1003,
    "name": "Actajuus",
    "trade_name": "Actajuus Sistema Jurídico",
    "cnpj": "10.123.456/0001-00",
    "address": {
        "id_address": 1,
        "zip": "12345-678",
        "title": "Avenida",
        "street": "Cariocas",
        "complement": "Casa 70",
        "reference": "Hospital Pedro Pedrossian",
        "number": 1450,
        "neighborhood": "Parque das Laranjeiras",
        "city": "Rio de Janeiro",
        "state": "Rio de Janeiro",
        "country": "Brasil"
    },
    "phone": {
        "id_phone": 1,
        "number": "+5567912341111",
        "kind": "Celular",
        "department": ""
    },
    "email": {
        "id_email": 6,
        "address": "falecomnos@acatajus.com.br"
    },
    "social_media": [
        {
            "id_social_media": 1,
            "platform": "facebook",
            "url": "https://www.facebook.com/acaatajus"
        },
        {
            "id_social_media": 2,
            "platform": "Linkedin",
            "url": "https://www.linkedin.com/in/acaatajus/"
        },
        {
            "id_social_media": 3,
            "platform": "Instagram",
            "url": "https://www.instagram.com/acaatajus/"
        },
        {
            "id_social_media": 4,
            "platform": "X",
            "url": "https://x.com/acaatajus"
        },
        {
            "id_social_media": 5,
            "platform": "Site",
            "url": "https://twitter.com/acaatajus"
        }
    ]
}

###
DELETE http://localhost:8080/companies
content-type: application/json

{
    "id_company": 2
}



###
POST https://api.actajus.com.br/auth/email
content-type: application/json

{
    "cpf": "111.444.777-35"
}


###
POST https://api.actajus.com.br/auth/recover
content-type: application/json

{
    "email": "marcelo@marcelo.eti.br"
}

###
POST https://api.actajus.com.br/auth/renew
content-type: application/json

{
    "cpf": "987.654.321-00",
    "password": "@Admin123",
    "token": "yNTZrWlOalljefSR-n3iEXHtji4PzA8K1fy9ASA5KcY="
}


###
POST https://api.actajus.com.br/signin
content-type: application/json

{
    "cpf": "111.444.777-35",
    "password": "@Admin123"
}

###
POST https://api.actajus.com.br/signin
content-type: application/json

{
    "cpf": "123.456.789-09",
    "password": "admin123"
}

###
POST https://api.actajus.com.br/signin
content-type: application/json

{
    "cpf": "987.654.321-00",
    "password": "admin123"
}

###
POST https://api.actajus.com.br/signin
content-type: application/json

{
    "cpf": "012.345.678-90",
    "password": "admin123"
}

###
POST https://api.actajus.com.br/signin
content-type: application/json

{
    "cpf": "714.602.380-01",
    "password": "admin123"
}







###
GET https://api.actajus.com.br/companies
content-type: application/json

###
POST https://api.actajus.com.br/companies/find/id
content-type: application/json

{
    "id": 1
}

###
POST https://api.actajus.com.br/companies/find/cnpj
content-type: application/json

{
    "cnpj": "48.922.852/0001-62"
}

# "cnpj": "03.015.475/0001-40"

###
POST https://api.actajus.com.br/companies
content-type: application/json

{
    "registered_by": 3,
    "name": "Actajus",
    "trade_name": "Actajus Sistema Jurídico",
    "cnpj": "91.715.885/0001-60",
    "address": {
        "zip": "12345-678",
        "title": "Avenida",
        "street": "Paulista",
        "complement": "Apartamento 123",
        "reference": "Perto da escola Izabel",
        "number": 123,
        "neighborhood": "Centro",
        "city": "São Paulo",
        "state": "São Paulo",
        "country": "Brasil"
    },
    "phone": {
        "number": "+5567912345678",
        "kind": "Celular",
        "department": "Comercial"
    },
    "email": {
        "address": "falecom22@acatajus.com.br"
    },
    "social_media": [
        {
            "platform": "facebook",
            "url": "https://www.facebook.com/actajus2s"
        },
        {
            "platform": "Linkedin",
            "url": "https://www.linkedin.com/in/actajus2s/"
        },
        {
            "platform": "Instagram",
            "url": "https://www.instagram.com/actajus2s/"
        },
        {
            "platform": "X",
            "url": "https://x.com/actajus2s"
        },
        {
            "platform": "Site",
            "url": "https://twitter.com/actajus2s"
        }
    ]
}


###
PUT  https://api.actajus.com.br/companies
content-type: application/json

{
    "id_company": 1,
    "name": "Actajuus",
    "trade_name": "Actajuus Sistema Jurídico",
    "cnpj": "10.123.456/0001-00",
    "address": {
        "id_address": 1,
        "zip": "12345-678",
        "title": "Avenida",
        "street": "Cariocas",
        "complement": "Casa 70",
        "reference": "Hospital Pedro Pedrossian",
        "number": 1450,
        "neighborhood": "Parque das Laranjeiras",
        "city": "Rio de Janeiro",
        "state": "Rio de Janeiro",
        "country": "Brasil"
    },
    "phone": {
        "id_phone": 1,
        "number": "+5567912341111",
        "kind": "Celular",
        "department": ""
    },
    "email": {
        "id_email": 6,
        "address": "falecomnos@acatajus.com.br"
    },
    "social_media": [
        {
            "id_social_media": 1,
            "platform": "facebook",
            "url": "https://www.facebook.com/acaatajus"
        },
        {
            "id_social_media": 2,
            "platform": "Linkedin",
            "url": "https://www.linkedin.com/in/acaatajus/"
        },
        {
            "id_social_media": 3,
            "platform": "Instagram",
            "url": "https://www.instagram.com/acaatajus/"
        },
        {
            "id_social_media": 4,
            "platform": "X",
            "url": "https://x.com/acaatajus"
        },
        {
            "id_social_media": 5,
            "platform": "Site",
            "url": "https://twitter.com/acaatajus"
        }
    ]
}

###
DELETE https://api.actajus.com.br/companies
content-type: application/json

{
    "id_company": 1
}


{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGFtcGxlLmNvbS5iciIsImV4cCI6MTc3MjA3MDkyMywiaWF0IjoxNzcyMDcwMDIzLCJpc3MiOiJzZXVfZG9taW5pby5jb20uYnIiLCJzaWQiOiIxIiwic3ViIjoiMyJ9.XwAOUPpfBIArwnTKY5izGgVkjYNQthQuVF3ixJCWxZc",
  "accessExpiresAt": "2026-02-26T01:55:23.685650484Z",
  "refreshToken": "BMiFphUzT0mlXqS7pwZGqu74bRo7l-cLywkL5nqvHdU",
  "refreshExpiresAt": "2026-02-27T01:40:23.685650484Z",
  "idSession": "1"
}


Response contents:
{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGFtcGxlLmNvbS5iciIsImV4cCI6MTc3MjA3MTQwOCwiaWF0IjoxNzcyMDcwNTA4LCJpc3MiOiJzZXVfZG9taW5pby5jb20uYnIiLCJzaWQiOiIyIiwic3ViIjoiMyJ9.KDknSWJ2-w-Qm5zulCYe3qTBfxpruZFdbmooBIYceks",
  "accessExpiresAt": "2026-02-26T02:03:28.292358691Z",
  "refreshToken": "_Cm1OhiIMulYm4F5UrMdW3hzkUbvX5gyK7diCPyw7bo",
  "refreshExpiresAt": "2026-02-27T01:48:28.292358691Z",
  "idSession": "2"
}


grpcurl -v \
-protoset <(buf build -o -) -plaintext \
-d '{"email":"marcelo@marcelo.eti.br","password":"Senha@123","ip":"127.0.0.1","user_agent":"grpcurl"}' \
localhost:8080 identity.v1.AuthService/Login

grpcurl -v \
-protoset <(buf build -o -) -plaintext \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGFtcGxlLmNvbS5iciIsImV4cCI6MTc3MjA3MDkyMywiaWF0IjoxNzcyMDcwMDIzLCJpc3MiOiJzZXVfZG9taW5pby5jb20uYnIiLCJzaWQiOiIxIiwic3ViIjoiMyJ9.XwAOUPpfBIArwnTKY5izGgVkjYNQthQuVF3ixJCWxZc" \
-d '{"name": "Fulano da Silva", "birthday": "27/05/1985", "gender": 1}' \
localhost:8080 person.v1.PersonService/CreatePerson


grpcurl -v \
-protoset <(buf build -o -) -plaintext \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGFtcGxlLmNvbS5iciIsImV4cCI6MTc3MjA3MTQwOCwiaWF0IjoxNzcyMDcwNTA4LCJpc3MiOiJzZXVfZG9taW5pby5jb20uYnIiLCJzaWQiOiIyIiwic3ViIjoiMyJ9.KDknSWJ2-w-Qm5zulCYe3qTBfxpruZFdbmooBIYceks" \
-d '{"name": "Fulano da Silva", "birthday": "27/05/1985", "gender": 1}' \
localhost:8080 person.v1.PersonService/CreatePerson

grpcurl -v \
-protoset <(buf build -o -) -plaintext \
-d '{"id_session":1,"refresh_token":"nGFso5bC_UHtYtGA9YHEfKNOdxFL_XA959Bt8USG-Sw","ip":"127.0.0.1","user_agent":"grpcurl"}' \
localhost:8080 identity.v1.AuthService/Refresh

grpcurl -v \
-protoset <(buf build -o -) -plaintext \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGFtcGxlLmNvbS5iciIsImV4cCI6MTc3MjA3MDkyMywiaWF0IjoxNzcyMDcwMDIzLCJpc3MiOiJzZXVfZG9taW5pby5jb20uYnIiLCJzaWQiOiIxIiwic3ViIjoiMyJ9.XwAOUPpfBIArwnTKY5izGgVkjYNQthQuVF3ixJCWxZc" \
-d '{"id_session":1}' \
localhost:8080 identity.v1.AuthService/Logout

grpcurl -v \
-protoset <(buf build -o -) -plaintext \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGFtcGxlLmNvbS5iciIsImV4cCI6MTc3MjA0NzM0NiwiaWF0IjoxNzcyMDQ2NDQ2LCJpc3MiOiJzZXVfZG9taW5pby5jb20uYnIiLCJzaWQiOiIxMiIsInN1YiI6IjMifQ.F-lPTM4qNSpQxLsBuoKKFa0doVlFEXTOfOqLJg5PYXA" \
-d '{"id_user":3}' \
localhost:8080 identity.v1.AuthService/LogoutAll

grpcurl -v \
-protoset <(buf build -o -) -plaintext \
-d '{"email":"marcelo@marcelo.eti.br2"}' \
localhost:8080 identity.v1.AuthService/RequestPasswordReset


Response contents:
{
  "ok": true,
  "idReset": "4",
  "resetToken": "aIxpTNxP-AdVC61g8hMiU6KlxYpGOS9kUiFQ66kNqD8",
  "expiresAt": "2026-02-26T01:50:11.935385030Z"
}






grpcurl -v \
-protoset <(buf build -o -) -plaintext \
-d '{"id_reset": 4, "reset_token":"aIxpTNxP-AdVC61g8hMiU6KlxYpGOS9kUiFQ66kNqD8","new_password":"Senha@123"}' \
localhost:8080 identity.v1.AuthService/ConfirmPasswordReset