POST http://localhost:8080/signin
content-type: application/json

{
    "cpf": "11144477735",
    "password": "admin123"
}

###
POST http://localhost:8080/auth/email
content-type: application/json

{
    "cpf": "11144477735"
}

###
POST http://localhost:8080/auth/recover
content-type: application/json

{
    "email": "marcelo@marcelo.eti.br"
}

###
POST http://localhost:8080/auth/renew
content-type: application/json

{
    "cpf": "111.444.777-35",
    "password": "!Admin123",
    "token": "tVtTlI5wXXcdrGpXhmis_75kfKxW1EkjJE6ggdBnUws="
}

###
GET http://localhost:8080/companies
content-type: application/json

###
POST http://localhost:8080/companies/find/id
content-type: application/json

{
    "id": 2
}

###
POST http://localhost:8080/companies/find/cnpj
content-type: application/json

{
    "cnpj": "48.922.852/0001-62"
}

# "cnpj": "03.015.475/0001-40"

###
POST http://localhost:8080/companies
content-type: application/json

{
    "registered_by": 3,
    "name": "Actajus",
    "trade_name": "Actajus Sistema Jurídico",
    "cnpj": "48.922.852/0001-62",
    "address": {
        "zip": "12345-678",
        "title": "Avenida",
        "street": "Paulista",
        "complement": "Apartamento 123",
        "reference": "Perto da escola Izabel",
        "number": 123,
        "neighborhood": "Centro",
        "city": "São Paulo",
        "state": "São Paulo",
        "country": "Brasil"
    },
    "phone": {
        "number": "+5567912345678",
        "kind": "Celular",
        "department": "Comercial"
    },
    "email": {
        "address": "falecosm2@acatajus.com.br"
    },
    "social_media": [
        {
            "platform": "facebook",
            "url": "https://www.facebook.com/asctajus2"
        },
        {
            "platform": "Linkedin",
            "url": "https://www.linkedin.com/in/actajsus2/"
        },
        {
            "platform": "Instagram",
            "url": "https://www.instagram.com/actajsus2/"
        },
        {
            "platform": "X",
            "url": "https://x.com/actajuss2"
        },
        {
            "platform": "Site",
            "url": "https://twitter.com/actasjus2"
        }
    ]
}


###
PUT  http://localhost:8080/companies
content-type: application/json

{
    "id_company": 1003,
    "name": "Actajuus",
    "trade_name": "Actajuus Sistema Jurídico",
    "cnpj": "10.123.456/0001-00",
    "address": {
        "id_address": 1,
        "zip": "12345-678",
        "title": "Avenida",
        "street": "Cariocas",
        "complement": "Casa 70",
        "reference": "Hospital Pedro Pedrossian",
        "number": 1450,
        "neighborhood": "Parque das Laranjeiras",
        "city": "Rio de Janeiro",
        "state": "Rio de Janeiro",
        "country": "Brasil"
    },
    "phone": {
        "id_phone": 1,
        "number": "+5567912341111",
        "kind": "Celular",
        "department": ""
    },
    "email": {
        "id_email": 6,
        "address": "falecomnos@acatajus.com.br"
    },
    "social_media": [
        {
            "id_social_media": 1,
            "platform": "facebook",
            "url": "https://www.facebook.com/acaatajus"
        },
        {
            "id_social_media": 2,
            "platform": "Linkedin",
            "url": "https://www.linkedin.com/in/acaatajus/"
        },
        {
            "id_social_media": 3,
            "platform": "Instagram",
            "url": "https://www.instagram.com/acaatajus/"
        },
        {
            "id_social_media": 4,
            "platform": "X",
            "url": "https://x.com/acaatajus"
        },
        {
            "id_social_media": 5,
            "platform": "Site",
            "url": "https://twitter.com/acaatajus"
        }
    ]
}

###
DELETE http://localhost:8080/companies
content-type: application/json

{
    "id_company": 2
}



###
POST https://api.actajus.com.br/auth/email
content-type: application/json

{
    "cpf": "111.444.777-35"
}


###
POST https://api.actajus.com.br/auth/recover
content-type: application/json

{
    "email": "marcelo@marcelo.eti.br"
}

###
POST https://api.actajus.com.br/auth/renew
content-type: application/json

{
    "cpf": "987.654.321-00",
    "password": "@Admin123",
    "token": "yNTZrWlOalljefSR-n3iEXHtji4PzA8K1fy9ASA5KcY="
}


###
POST https://api.actajus.com.br/signin
content-type: application/json

{
    "cpf": "111.444.777-35",
    "password": "@Admin123"
}

###
POST https://api.actajus.com.br/signin
content-type: application/json

{
    "cpf": "123.456.789-09",
    "password": "admin123"
}

###
POST https://api.actajus.com.br/signin
content-type: application/json

{
    "cpf": "987.654.321-00",
    "password": "admin123"
}

###
POST https://api.actajus.com.br/signin
content-type: application/json

{
    "cpf": "012.345.678-90",
    "password": "admin123"
}

###
POST https://api.actajus.com.br/signin
content-type: application/json

{
    "cpf": "714.602.380-01",
    "password": "admin123"
}







###
GET https://api.actajus.com.br/companies
content-type: application/json

###
POST https://api.actajus.com.br/companies/find/id
content-type: application/json

{
    "id": 1
}

###
POST https://api.actajus.com.br/companies/find/cnpj
content-type: application/json

{
    "cnpj": "48.922.852/0001-62"
}

# "cnpj": "03.015.475/0001-40"

###
POST https://api.actajus.com.br/companies
content-type: application/json

{
    "registered_by": 3,
    "name": "Actajus",
    "trade_name": "Actajus Sistema Jurídico",
    "cnpj": "91.715.885/0001-60",
    "address": {
        "zip": "12345-678",
        "title": "Avenida",
        "street": "Paulista",
        "complement": "Apartamento 123",
        "reference": "Perto da escola Izabel",
        "number": 123,
        "neighborhood": "Centro",
        "city": "São Paulo",
        "state": "São Paulo",
        "country": "Brasil"
    },
    "phone": {
        "number": "+5567912345678",
        "kind": "Celular",
        "department": "Comercial"
    },
    "email": {
        "address": "falecom22@acatajus.com.br"
    },
    "social_media": [
        {
            "platform": "facebook",
            "url": "https://www.facebook.com/actajus2s"
        },
        {
            "platform": "Linkedin",
            "url": "https://www.linkedin.com/in/actajus2s/"
        },
        {
            "platform": "Instagram",
            "url": "https://www.instagram.com/actajus2s/"
        },
        {
            "platform": "X",
            "url": "https://x.com/actajus2s"
        },
        {
            "platform": "Site",
            "url": "https://twitter.com/actajus2s"
        }
    ]
}


###
PUT  https://api.actajus.com.br/companies
content-type: application/json

{
    "id_company": 1,
    "name": "Actajuus",
    "trade_name": "Actajuus Sistema Jurídico",
    "cnpj": "10.123.456/0001-00",
    "address": {
        "id_address": 1,
        "zip": "12345-678",
        "title": "Avenida",
        "street": "Cariocas",
        "complement": "Casa 70",
        "reference": "Hospital Pedro Pedrossian",
        "number": 1450,
        "neighborhood": "Parque das Laranjeiras",
        "city": "Rio de Janeiro",
        "state": "Rio de Janeiro",
        "country": "Brasil"
    },
    "phone": {
        "id_phone": 1,
        "number": "+5567912341111",
        "kind": "Celular",
        "department": ""
    },
    "email": {
        "id_email": 6,
        "address": "falecomnos@acatajus.com.br"
    },
    "social_media": [
        {
            "id_social_media": 1,
            "platform": "facebook",
            "url": "https://www.facebook.com/acaatajus"
        },
        {
            "id_social_media": 2,
            "platform": "Linkedin",
            "url": "https://www.linkedin.com/in/acaatajus/"
        },
        {
            "id_social_media": 3,
            "platform": "Instagram",
            "url": "https://www.instagram.com/acaatajus/"
        },
        {
            "id_social_media": 4,
            "platform": "X",
            "url": "https://x.com/acaatajus"
        },
        {
            "id_social_media": 5,
            "platform": "Site",
            "url": "https://twitter.com/acaatajus"
        }
    ]
}

###
DELETE https://api.actajus.com.br/companies
content-type: application/json

{
    "id_company": 1
}


{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGFtcGxlLmNvbS5iciIsImV4cCI6MTc3MjY1MzU4OSwiaWF0IjoxNzcyNjUyNjg5LCJpc3MiOiJzZXVfZG9taW5pby5jb20uYnIiLCJzaWQiOiIxIiwic3ViIjoiMyJ9.aOcB1Ug1XVGebxRyg-5nPZw8Z0HkWIoKnR0-PwDKP-4",
  "accessExpiresAt": "2026-03-04T19:46:29.681078883Z",
  "refreshToken": "aCNIJKqpEfo86dwk7rVwwRO8CBmsEcdSEw0mLgx5dcQ",
  "refreshExpiresAt": "2026-03-05T19:31:29.681078883Z",
  "idSession": "1"
}

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGFtcGxlLmNvbS5iciIsImV4cCI6MTc3MjU1MzE0MCwiaWF0IjoxNzcyNTUyMjQwLCJpc3MiOiJzZXVfZG9taW5pby5jb20uYnIiLCJzaWQiOiIyIiwic3ViIjoiMyJ9.6_ukPhfkguJCZ8w-V3Ltqq-ovC-z67D1gw8VJ9vxfSM",
  "accessExpiresAt": "2026-03-03T15:52:20.074822256Z",
  "refreshToken": "LHEPQ735PkEiRmPc4eFQ4YzS95W0Ghn4Qy2kFaOAHm0",
  "refreshExpiresAt": "2026-03-04T15:37:20.074822256Z",
  "idSession": "2"
}

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGFtcGxlLmNvbS5iciIsImV4cCI6MTc3MjY1MzY4MCwiaWF0IjoxNzcyNjUyNzgwLCJpc3MiOiJzZXVfZG9taW5pby5jb20uYnIiLCJzaWQiOiIzIiwic3ViIjoiMyJ9.ZMdwLwg3mAI1_RBUavswraP6d6mLNvURsMRH1I7HNJA",
  "accessExpiresAt": "2026-03-04T19:48:00.810141668Z",
  "refreshToken": "_oXojjiKICTuStjUeHRgk5WIEYRVnKar4Z5pteFFdrw",
  "refreshExpiresAt": "2026-03-05T19:33:00.810141668Z",
  "idSession": "3"
}

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGFtcGxlLmNvbS5iciIsImV4cCI6MTc3MjA3MTQwOCwiaWF0IjoxNzcyMDcwNTA4LCJpc3MiOiJzZXVfZG9taW5pby5jb20uYnIiLCJzaWQiOiIyIiwic3ViIjoiMyJ9.KDknSWJ2-w-Qm5zulCYe3qTBfxpruZFdbmooBIYceks",
  "accessExpiresAt": "2026-02-26T02:03:28.292358691Z",
  "refreshToken": "_Cm1OhiIMulYm4F5UrMdW3hzkUbvX5gyK7diCPyw7bo",
  "refreshExpiresAt": "2026-02-27T01:48:28.292358691Z",
  "idSession": "2"
}

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGFtcGxlLmNvbS5iciIsImV4cCI6MTc3MjU1MTM1NiwiaWF0IjoxNzcyNTUwNDU2LCJpc3MiOiJzZXVfZG9taW5pby5jb20uYnIiLCJzaWQiOiIxIiwic3ViIjoiMyJ9.Kl_73jVrCKUPNr2T_fr9Tdw1q-mDVEIVcV089UQM7hY",
  "accessExpiresAt": "2026-03-03T15:22:36.743371188Z",
  "refreshToken": "d-7m2i9nGltcVbR46dC3j1UVVS9R3xqzOCqmJW_DMKU",
  "refreshExpiresAt": "2026-03-04T15:07:36.743371188Z",
  "idSession": "1"
}


grpcurl -v \
-protoset <(buf build -o -) -plaintext \
-d '{"email":"marcelo@marcelo.eti.br","password":"Senha@123","ip":"127.0.0.1","user_agent":"grpcurl"}' \
localhost:50051 identity.v1.AuthService/Login

grpcurl -v \
-protoset <(buf build -o -) -plaintext \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGFtcGxlLmNvbS5iciIsImV4cCI6MTc3MjY1MzU4OSwiaWF0IjoxNzcyNjUyNjg5LCJpc3MiOiJzZXVfZG9taW5pby5jb20uYnIiLCJzaWQiOiIxIiwic3ViIjoiMyJ9.aOcB1Ug1XVGebxRyg-5nPZw8Z0HkWIoKnR0-PwDKP-4" \
-d '{"name": "Fulano da Silva", "birthday": "27/05/1985", "gender": 1}' \
localhost:50051 person.v1.PersonService/CreatePerson


grpcurl -v \
-protoset <(buf build -o -) -plaintext \
-d '{"id_session":1,"refresh_token":"Pv0kR5Ch-SHRYJJVliDTtiyj_5nhRAvrrVZu6-kmebk","ip":"127.0.0.1","user_agent":"grpcurl"}' \
localhost:50051 identity.v1.AuthService/Refresh



grpcurl -v \
-protoset <(buf build -o -) -plaintext \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGFtcGxlLmNvbS5iciIsImV4cCI6MTc3MjU1MzE0MCwiaWF0IjoxNzcyNTUyMjQwLCJpc3MiOiJzZXVfZG9taW5pby5jb20uYnIiLCJzaWQiOiIyIiwic3ViIjoiMyJ9.6_ukPhfkguJCZ8w-V3Ltqq-ovC-z67D1gw8VJ9vxfSM" \
-d '{"id_session":2}' \
localhost:50051 identity.v1.AuthService/Logout

grpcurl -v \
-protoset <(buf build -o -) -plaintext \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGFtcGxlLmNvbS5iciIsImV4cCI6MTc3MjU1MzE0MCwiaWF0IjoxNzcyNTUyMjQwLCJpc3MiOiJzZXVfZG9taW5pby5jb20uYnIiLCJzaWQiOiIyIiwic3ViIjoiMyJ9.6_ukPhfkguJCZ8w-V3Ltqq-ovC-z67D1gw8VJ9vxfSM" \
-d '{"id_user":3}' \
localhost:50051 identity.v1.AuthService/LogoutAll

grpcurl -v \
-protoset <(buf build -o -) -plaintext \
-d '{"email":"marcelo@marcelo.eti.br2"}' \
localhost:50051 identity.v1.AuthService/RequestPasswordReset

grpcurl -v \
-protoset <(buf build -o -) -plaintext \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGFtcGxlLmNvbS5iciIsImV4cCI6MTc3MjU1MzY5OCwiaWF0IjoxNzcyNTUyNzk4LCJpc3MiOiJzZXVfZG9taW5pby5jb20uYnIiLCJzaWQiOiIxIiwic3ViIjoiMyJ9.SP5mlfC6FXeEmmMlWm56YzCZ87tZe0HyEL0dgsH50ao" \
-d '{"id_user":4,"id_role":3,"assigned_by":3}' \
localhost:50051 identity.v1.RbacAdminService/AssignRoleToUser


grpcurl -v \
-protoset <(buf build -o -) -plaintext \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGFtcGxlLmNvbS5iciIsImV4cCI6MTc3MjU1MzY5OCwiaWF0IjoxNzcyNTUyNzk4LCJpc3MiOiJzZXVfZG9taW5pby5jb20uYnIiLCJzaWQiOiIxIiwic3ViIjoiMyJ9.SP5mlfC6FXeEmmMlWm56YzCZ87tZe0HyEL0dgsH50ao" \
-d '{ "id_user":3,"id_role":6 }' \
localhost:50051 identity.v1.RbacAdminService/RemoveRoleFromUser

grpcurl -v \
-protoset <(buf build -o -) -plaintext \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGFtcGxlLmNvbS5iciIsImV4cCI6MTc3MjU1MzY5OCwiaWF0IjoxNzcyNTUyNzk4LCJpc3MiOiJzZXVfZG9taW5pby5jb20uYnIiLCJzaWQiOiIxIiwic3ViIjoiMyJ9.SP5mlfC6FXeEmmMlWm56YzCZ87tZe0HyEL0dgsH50ao" \
  -d '{"id_role":1,"id_permission":5}' \
  localhost:50051 identity.v1.RbacAdminService/GrantPermissionToRole

Response contents:
{
  "ok": true,
  "idReset": "1",
  "resetToken": "h651SFQgycaEdRYXzhcAgdx_NpIdHUxJDZb74tkei4U",
  "expiresAt": "2026-03-03T15:57:32.662358383Z"
}

{
  "ok": true,
  "idReset": "2",
  "resetToken": "Qv0p90IZEjlW8VW2DjXvq_Cr6_w5bWeJ2g1WwDnYI3g",
  "expiresAt": "2026-03-04T20:28:24.619084248Z"
}



grpcurl -v \
-protoset <(buf build -o -) -plaintext \
-d '{"id_reset": 2, "reset_token":"Qv0p90IZEjlW8VW2DjXvq_Cr6_w5bWeJ2g1WwDnYI3g","new_password":"Senha@123"}' \
localhost:50051 identity.v1.AuthService/ConfirmPasswordReset

  curl --request POST \
  --url http://172.16.0.6:8080/message/sendText/tidof \
  --header 'Content-Type: application/json' \
  --header 'apikey: 01HKT7JE6W173PXW85PGZXXZRB' \
  --data '
{
  "number": "+5567999417840",
  "text": "Teste de envio de mensagem",
  "delay": 123
}
'


KEYS "rbac:*"
KEYS "actajus:session:*"

SMEMBERS rbac:user_perms:3
TTL rbac:user_perms:3

SMEMBERS rbac:role_users:1

GET actajus:session:5
DEL rbac:user_perms:3
DEL actajus:session:5


-- sessões
SELECT idsessions, id_users, revoked_at, rotated_at, expires_at, updated_at
FROM sessions
ORDER BY idsessions DESC;

-- resets
SELECT idpassword_resets, id_users, used_at, expires_at, created_at
FROM password_resets
ORDER BY idpassword_resets DESC;

-- roles do user
SELECT ru.id_users, ru.id_roles, r.code
FROM role_user ru
JOIN roles r ON r.idroles = ru.id_roles
WHERE ru.id_users = 3;

-- permissões efetivas do user
SELECT DISTINCT (p.resource || ':' || p.action) AS perm
FROM role_user ru
JOIN permission_role pr ON pr.id_roles = ru.id_roles
JOIN permissions p ON p.idpermissions = pr.id_permissions
WHERE ru.id_users = 3
ORDER BY perm;


