POST http://localhost:8080/signin
content-type: application/json

{
    "cpf": "11144477735",
    "password": "admin123"
}

###
POST http://localhost:8080/auth/email
content-type: application/json

{
    "cpf": "11144477735"
}

###
POST http://localhost:8080/auth/recover
content-type: application/json

{
    "email": "marcelo@marcelo.eti.br"
}

###
POST http://localhost:8080/auth/renew
content-type: application/json

{
    "cpf": "111.444.777-35",
    "password": "!Admin123",
    "token": "tVtTlI5wXXcdrGpXhmis_75kfKxW1EkjJE6ggdBnUws="
}

###
POST http://localhost:8080/enterprise
content-type: application/json

{
    "enterprise": {
        "registered_by": 3,
        "name": "Actajus",
        "trade_name": "Actajus sistema jurídico",
        "cnpj": "10.123.456/0001-00"
    },
    "address": {
        "zip": "12345-678",
        "title": "Avenida",
        "street": "Paulista",
        "complement": "Apartamento 123",
        "number": 123,
        "neighborhood": "Centro",
        "city": "São Paulo",
        "state": "",
        "country": "Brasil"
    }   
}


###
POST https://api.actajus.com.br/auth/email
content-type: application/json

{
    "cpf": "111.444.777-35"
}


###
POST https://api.actajus.com.br/auth/recover
content-type: application/json

{
    "email": "marcelo@marcelo.eti.br"
}

###
POST https://api.actajus.com.br/auth/renew
content-type: application/json

{
    "cpf": "987.654.321-00",
    "password": "@Admin123",
    "token": "yNTZrWlOalljefSR-n3iEXHtji4PzA8K1fy9ASA5KcY="
}


###
POST https://api.actajus.com.br/signin
content-type: application/json

{
    "cpf": "111.444.777-35",
    "password": "@Admin123"
}

###
POST https://api.actajus.com.br/signin
content-type: application/json

{
    "cpf": "123.456.789-09",
    "password": "admin123"
}

###
POST https://api.actajus.com.br/signin
content-type: application/json

{
    "cpf": "987.654.321-00",
    "password": "admin123"
}

###
POST https://api.actajus.com.br/signin
content-type: application/json

{
    "cpf": "012.345.678-90",
    "password": "admin123"
}

###
POST https://api.actajus.com.br/signin
content-type: application/json

{
    "cpf": "714.602.380-01",
    "password": "admin123"
}