// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: phone/v1/phone.proto

package phonev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/paladignus/actajus/proto/phone/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// PhoneServiceName is the fully-qualified name of the PhoneService service.
	PhoneServiceName = "phone.v1.PhoneService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PhoneServiceCreatePhoneProcedure is the fully-qualified name of the PhoneService's CreatePhone
	// RPC.
	PhoneServiceCreatePhoneProcedure = "/phone.v1.PhoneService/CreatePhone"
	// PhoneServiceUpdatePhoneProcedure is the fully-qualified name of the PhoneService's UpdatePhone
	// RPC.
	PhoneServiceUpdatePhoneProcedure = "/phone.v1.PhoneService/UpdatePhone"
)

// PhoneServiceClient is a client for the phone.v1.PhoneService service.
type PhoneServiceClient interface {
	CreatePhone(context.Context, *connect.Request[v1.CreatePhoneRequest]) (*connect.Response[v1.CreatePhoneResponse], error)
	UpdatePhone(context.Context, *connect.Request[v1.UpdatePhoneRequest]) (*connect.Response[v1.UpdatePhoneResponse], error)
}

// NewPhoneServiceClient constructs a client for the phone.v1.PhoneService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPhoneServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PhoneServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &phoneServiceClient{
		createPhone: connect.NewClient[v1.CreatePhoneRequest, v1.CreatePhoneResponse](
			httpClient,
			baseURL+PhoneServiceCreatePhoneProcedure,
			opts...,
		),
		updatePhone: connect.NewClient[v1.UpdatePhoneRequest, v1.UpdatePhoneResponse](
			httpClient,
			baseURL+PhoneServiceUpdatePhoneProcedure,
			opts...,
		),
	}
}

// phoneServiceClient implements PhoneServiceClient.
type phoneServiceClient struct {
	createPhone *connect.Client[v1.CreatePhoneRequest, v1.CreatePhoneResponse]
	updatePhone *connect.Client[v1.UpdatePhoneRequest, v1.UpdatePhoneResponse]
}

// CreatePhone calls phone.v1.PhoneService.CreatePhone.
func (c *phoneServiceClient) CreatePhone(ctx context.Context, req *connect.Request[v1.CreatePhoneRequest]) (*connect.Response[v1.CreatePhoneResponse], error) {
	return c.createPhone.CallUnary(ctx, req)
}

// UpdatePhone calls phone.v1.PhoneService.UpdatePhone.
func (c *phoneServiceClient) UpdatePhone(ctx context.Context, req *connect.Request[v1.UpdatePhoneRequest]) (*connect.Response[v1.UpdatePhoneResponse], error) {
	return c.updatePhone.CallUnary(ctx, req)
}

// PhoneServiceHandler is an implementation of the phone.v1.PhoneService service.
type PhoneServiceHandler interface {
	CreatePhone(context.Context, *connect.Request[v1.CreatePhoneRequest]) (*connect.Response[v1.CreatePhoneResponse], error)
	UpdatePhone(context.Context, *connect.Request[v1.UpdatePhoneRequest]) (*connect.Response[v1.UpdatePhoneResponse], error)
}

// NewPhoneServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPhoneServiceHandler(svc PhoneServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	phoneServiceCreatePhoneHandler := connect.NewUnaryHandler(
		PhoneServiceCreatePhoneProcedure,
		svc.CreatePhone,
		opts...,
	)
	phoneServiceUpdatePhoneHandler := connect.NewUnaryHandler(
		PhoneServiceUpdatePhoneProcedure,
		svc.UpdatePhone,
		opts...,
	)
	return "/phone.v1.PhoneService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PhoneServiceCreatePhoneProcedure:
			phoneServiceCreatePhoneHandler.ServeHTTP(w, r)
		case PhoneServiceUpdatePhoneProcedure:
			phoneServiceUpdatePhoneHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPhoneServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPhoneServiceHandler struct{}

func (UnimplementedPhoneServiceHandler) CreatePhone(context.Context, *connect.Request[v1.CreatePhoneRequest]) (*connect.Response[v1.CreatePhoneResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("phone.v1.PhoneService.CreatePhone is not implemented"))
}

func (UnimplementedPhoneServiceHandler) UpdatePhone(context.Context, *connect.Request[v1.UpdatePhoneRequest]) (*connect.Response[v1.UpdatePhoneResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("phone.v1.PhoneService.UpdatePhone is not implemented"))
}
