// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: social_media/v1/social_media.proto

package socialmediav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSocialMediaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Platform string `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Url      string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *CreateSocialMediaRequest) Reset() {
	*x = CreateSocialMediaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_media_v1_social_media_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSocialMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSocialMediaRequest) ProtoMessage() {}

func (x *CreateSocialMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_media_v1_social_media_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSocialMediaRequest.ProtoReflect.Descriptor instead.
func (*CreateSocialMediaRequest) Descriptor() ([]byte, []int) {
	return file_social_media_v1_social_media_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSocialMediaRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateSocialMediaRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateSocialMediaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []int64 `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateSocialMediaResponse) Reset() {
	*x = CreateSocialMediaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_media_v1_social_media_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSocialMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSocialMediaResponse) ProtoMessage() {}

func (x *CreateSocialMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_media_v1_social_media_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSocialMediaResponse.ProtoReflect.Descriptor instead.
func (*CreateSocialMediaResponse) Descriptor() ([]byte, []int) {
	return file_social_media_v1_social_media_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSocialMediaResponse) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

type UpdateSocialMediaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Url      string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *UpdateSocialMediaRequest) Reset() {
	*x = UpdateSocialMediaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_media_v1_social_media_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSocialMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSocialMediaRequest) ProtoMessage() {}

func (x *UpdateSocialMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_media_v1_social_media_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSocialMediaRequest.ProtoReflect.Descriptor instead.
func (*UpdateSocialMediaRequest) Descriptor() ([]byte, []int) {
	return file_social_media_v1_social_media_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateSocialMediaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSocialMediaRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UpdateSocialMediaRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UpdateSocialMediaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []int64 `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdateSocialMediaResponse) Reset() {
	*x = UpdateSocialMediaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_media_v1_social_media_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSocialMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSocialMediaResponse) ProtoMessage() {}

func (x *UpdateSocialMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_media_v1_social_media_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSocialMediaResponse.ProtoReflect.Descriptor instead.
func (*UpdateSocialMediaResponse) Descriptor() ([]byte, []int) {
	return file_social_media_v1_social_media_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSocialMediaResponse) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

var File_social_media_v1_social_media_proto protoreflect.FileDescriptor

var file_social_media_v1_social_media_proto_rawDesc = []byte{
	0x0a, 0x22, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x2e, 0x76, 0x31, 0x22, 0x48, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22,
	0x2b, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x58, 0x0a, 0x18,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x2b, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x32, 0xec, 0x01, 0x0a, 0x12, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6a, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x12,
	0x29, 0x2e, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x73, 0x6f, 0x63,
	0x69, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6a, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x29, 0x2e, 0x73, 0x6f,
	0x63, 0x69, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x70, 0x61, 0x6c, 0x61, 0x64, 0x69, 0x67, 0x6e, 0x75, 0x73, 0x2f, 0x61, 0x63, 0x74, 0x61,
	0x6a, 0x75, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c,
	0x5f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_social_media_v1_social_media_proto_rawDescOnce sync.Once
	file_social_media_v1_social_media_proto_rawDescData = file_social_media_v1_social_media_proto_rawDesc
)

func file_social_media_v1_social_media_proto_rawDescGZIP() []byte {
	file_social_media_v1_social_media_proto_rawDescOnce.Do(func() {
		file_social_media_v1_social_media_proto_rawDescData = protoimpl.X.CompressGZIP(file_social_media_v1_social_media_proto_rawDescData)
	})
	return file_social_media_v1_social_media_proto_rawDescData
}

var file_social_media_v1_social_media_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_social_media_v1_social_media_proto_goTypes = []interface{}{
	(*CreateSocialMediaRequest)(nil),  // 0: social_media.v1.CreateSocialMediaRequest
	(*CreateSocialMediaResponse)(nil), // 1: social_media.v1.CreateSocialMediaResponse
	(*UpdateSocialMediaRequest)(nil),  // 2: social_media.v1.UpdateSocialMediaRequest
	(*UpdateSocialMediaResponse)(nil), // 3: social_media.v1.UpdateSocialMediaResponse
}
var file_social_media_v1_social_media_proto_depIdxs = []int32{
	0, // 0: social_media.v1.SocialMediaService.CreateSocialMedia:input_type -> social_media.v1.CreateSocialMediaRequest
	2, // 1: social_media.v1.SocialMediaService.UpdateSocialMedia:input_type -> social_media.v1.UpdateSocialMediaRequest
	1, // 2: social_media.v1.SocialMediaService.CreateSocialMedia:output_type -> social_media.v1.CreateSocialMediaResponse
	3, // 3: social_media.v1.SocialMediaService.UpdateSocialMedia:output_type -> social_media.v1.UpdateSocialMediaResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_social_media_v1_social_media_proto_init() }
func file_social_media_v1_social_media_proto_init() {
	if File_social_media_v1_social_media_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_social_media_v1_social_media_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSocialMediaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_media_v1_social_media_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSocialMediaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_media_v1_social_media_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSocialMediaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_media_v1_social_media_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSocialMediaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_social_media_v1_social_media_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_social_media_v1_social_media_proto_goTypes,
		DependencyIndexes: file_social_media_v1_social_media_proto_depIdxs,
		MessageInfos:      file_social_media_v1_social_media_proto_msgTypes,
	}.Build()
	File_social_media_v1_social_media_proto = out.File
	file_social_media_v1_social_media_proto_rawDesc = nil
	file_social_media_v1_social_media_proto_goTypes = nil
	file_social_media_v1_social_media_proto_depIdxs = nil
}
