// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: person/v1/person.proto

package personv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/paladignus/actajus/proto/person/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// PersonServiceName is the fully-qualified name of the PersonService service.
	PersonServiceName = "person.v1.PersonService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PersonServiceCreatePersonProcedure is the fully-qualified name of the PersonService's
	// CreatePerson RPC.
	PersonServiceCreatePersonProcedure = "/person.v1.PersonService/CreatePerson"
)

// PersonServiceClient is a client for the person.v1.PersonService service.
type PersonServiceClient interface {
	CreatePerson(context.Context, *connect.Request[v1.CreatePersonRequest]) (*connect.Response[v1.CreatePersonResponse], error)
}

// NewPersonServiceClient constructs a client for the person.v1.PersonService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPersonServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PersonServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &personServiceClient{
		createPerson: connect.NewClient[v1.CreatePersonRequest, v1.CreatePersonResponse](
			httpClient,
			baseURL+PersonServiceCreatePersonProcedure,
			opts...,
		),
	}
}

// personServiceClient implements PersonServiceClient.
type personServiceClient struct {
	createPerson *connect.Client[v1.CreatePersonRequest, v1.CreatePersonResponse]
}

// CreatePerson calls person.v1.PersonService.CreatePerson.
func (c *personServiceClient) CreatePerson(ctx context.Context, req *connect.Request[v1.CreatePersonRequest]) (*connect.Response[v1.CreatePersonResponse], error) {
	return c.createPerson.CallUnary(ctx, req)
}

// PersonServiceHandler is an implementation of the person.v1.PersonService service.
type PersonServiceHandler interface {
	CreatePerson(context.Context, *connect.Request[v1.CreatePersonRequest]) (*connect.Response[v1.CreatePersonResponse], error)
}

// NewPersonServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPersonServiceHandler(svc PersonServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	personServiceCreatePersonHandler := connect.NewUnaryHandler(
		PersonServiceCreatePersonProcedure,
		svc.CreatePerson,
		opts...,
	)
	return "/person.v1.PersonService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PersonServiceCreatePersonProcedure:
			personServiceCreatePersonHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPersonServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPersonServiceHandler struct{}

func (UnimplementedPersonServiceHandler) CreatePerson(context.Context, *connect.Request[v1.CreatePersonRequest]) (*connect.Response[v1.CreatePersonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("person.v1.PersonService.CreatePerson is not implemented"))
}
