// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: phone/v1/phone.proto

package phonev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePhoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number     string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Kind       string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Department string `protobuf:"bytes,3,opt,name=department,proto3" json:"department,omitempty"`
}

func (x *CreatePhoneRequest) Reset() {
	*x = CreatePhoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phone_v1_phone_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePhoneRequest) ProtoMessage() {}

func (x *CreatePhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phone_v1_phone_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePhoneRequest.ProtoReflect.Descriptor instead.
func (*CreatePhoneRequest) Descriptor() ([]byte, []int) {
	return file_phone_v1_phone_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePhoneRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CreatePhoneRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CreatePhoneRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

type CreatePhoneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreatePhoneResponse) Reset() {
	*x = CreatePhoneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phone_v1_phone_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePhoneResponse) ProtoMessage() {}

func (x *CreatePhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phone_v1_phone_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePhoneResponse.ProtoReflect.Descriptor instead.
func (*CreatePhoneResponse) Descriptor() ([]byte, []int) {
	return file_phone_v1_phone_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePhoneResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdatePhoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number     string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Kind       string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Department string `protobuf:"bytes,4,opt,name=department,proto3" json:"department,omitempty"`
}

func (x *UpdatePhoneRequest) Reset() {
	*x = UpdatePhoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phone_v1_phone_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePhoneRequest) ProtoMessage() {}

func (x *UpdatePhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phone_v1_phone_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePhoneRequest.ProtoReflect.Descriptor instead.
func (*UpdatePhoneRequest) Descriptor() ([]byte, []int) {
	return file_phone_v1_phone_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePhoneRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePhoneRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *UpdatePhoneRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *UpdatePhoneRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

type UpdatePhoneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdatePhoneResponse) Reset() {
	*x = UpdatePhoneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phone_v1_phone_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePhoneResponse) ProtoMessage() {}

func (x *UpdatePhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phone_v1_phone_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePhoneResponse.ProtoReflect.Descriptor instead.
func (*UpdatePhoneResponse) Descriptor() ([]byte, []int) {
	return file_phone_v1_phone_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePhoneResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_phone_v1_phone_proto protoreflect.FileDescriptor

var file_phone_v1_phone_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x2e, 0x76, 0x31,
	0x22, 0x60, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0x25, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x70, 0x0a, 0x12, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x25, 0x0a, 0x13, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x32, 0xa6, 0x01, 0x0a, 0x0c, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4a, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1c,
	0x2e, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x6c, 0x61, 0x64, 0x69,
	0x67, 0x6e, 0x75, 0x73, 0x2f, 0x61, 0x63, 0x74, 0x61, 0x6a, 0x75, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_phone_v1_phone_proto_rawDescOnce sync.Once
	file_phone_v1_phone_proto_rawDescData = file_phone_v1_phone_proto_rawDesc
)

func file_phone_v1_phone_proto_rawDescGZIP() []byte {
	file_phone_v1_phone_proto_rawDescOnce.Do(func() {
		file_phone_v1_phone_proto_rawDescData = protoimpl.X.CompressGZIP(file_phone_v1_phone_proto_rawDescData)
	})
	return file_phone_v1_phone_proto_rawDescData
}

var file_phone_v1_phone_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_phone_v1_phone_proto_goTypes = []interface{}{
	(*CreatePhoneRequest)(nil),  // 0: phone.v1.CreatePhoneRequest
	(*CreatePhoneResponse)(nil), // 1: phone.v1.CreatePhoneResponse
	(*UpdatePhoneRequest)(nil),  // 2: phone.v1.UpdatePhoneRequest
	(*UpdatePhoneResponse)(nil), // 3: phone.v1.UpdatePhoneResponse
}
var file_phone_v1_phone_proto_depIdxs = []int32{
	0, // 0: phone.v1.PhoneService.CreatePhone:input_type -> phone.v1.CreatePhoneRequest
	2, // 1: phone.v1.PhoneService.UpdatePhone:input_type -> phone.v1.UpdatePhoneRequest
	1, // 2: phone.v1.PhoneService.CreatePhone:output_type -> phone.v1.CreatePhoneResponse
	3, // 3: phone.v1.PhoneService.UpdatePhone:output_type -> phone.v1.UpdatePhoneResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_phone_v1_phone_proto_init() }
func file_phone_v1_phone_proto_init() {
	if File_phone_v1_phone_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_phone_v1_phone_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePhoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phone_v1_phone_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePhoneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phone_v1_phone_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePhoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phone_v1_phone_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePhoneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_phone_v1_phone_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_phone_v1_phone_proto_goTypes,
		DependencyIndexes: file_phone_v1_phone_proto_depIdxs,
		MessageInfos:      file_phone_v1_phone_proto_msgTypes,
	}.Build()
	File_phone_v1_phone_proto = out.File
	file_phone_v1_phone_proto_rawDesc = nil
	file_phone_v1_phone_proto_goTypes = nil
	file_phone_v1_phone_proto_depIdxs = nil
}
