// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: address/v1/address.proto

package addressv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/paladignus/actajus/proto/address/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// AddressServiceName is the fully-qualified name of the AddressService service.
	AddressServiceName = "address.v1.AddressService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AddressServiceCreateAddressProcedure is the fully-qualified name of the AddressService's
	// CreateAddress RPC.
	AddressServiceCreateAddressProcedure = "/address.v1.AddressService/CreateAddress"
)

// AddressServiceClient is a client for the address.v1.AddressService service.
type AddressServiceClient interface {
	CreateAddress(context.Context, *connect.Request[v1.CreateAddressRequest]) (*connect.Response[v1.CreateAddressResponse], error)
}

// NewAddressServiceClient constructs a client for the address.v1.AddressService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAddressServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AddressServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &addressServiceClient{
		createAddress: connect.NewClient[v1.CreateAddressRequest, v1.CreateAddressResponse](
			httpClient,
			baseURL+AddressServiceCreateAddressProcedure,
			opts...,
		),
	}
}

// addressServiceClient implements AddressServiceClient.
type addressServiceClient struct {
	createAddress *connect.Client[v1.CreateAddressRequest, v1.CreateAddressResponse]
}

// CreateAddress calls address.v1.AddressService.CreateAddress.
func (c *addressServiceClient) CreateAddress(ctx context.Context, req *connect.Request[v1.CreateAddressRequest]) (*connect.Response[v1.CreateAddressResponse], error) {
	return c.createAddress.CallUnary(ctx, req)
}

// AddressServiceHandler is an implementation of the address.v1.AddressService service.
type AddressServiceHandler interface {
	CreateAddress(context.Context, *connect.Request[v1.CreateAddressRequest]) (*connect.Response[v1.CreateAddressResponse], error)
}

// NewAddressServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAddressServiceHandler(svc AddressServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	addressServiceCreateAddressHandler := connect.NewUnaryHandler(
		AddressServiceCreateAddressProcedure,
		svc.CreateAddress,
		opts...,
	)
	return "/address.v1.AddressService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AddressServiceCreateAddressProcedure:
			addressServiceCreateAddressHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAddressServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAddressServiceHandler struct{}

func (UnimplementedAddressServiceHandler) CreateAddress(context.Context, *connect.Request[v1.CreateAddressRequest]) (*connect.Response[v1.CreateAddressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("address.v1.AddressService.CreateAddress is not implemented"))
}
