// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: social_media/v1/social_media.proto

package socialmediav1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/paladignus/actajus/proto/social_media/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// SocialMediaServiceName is the fully-qualified name of the SocialMediaService service.
	SocialMediaServiceName = "social_media.v1.SocialMediaService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SocialMediaServiceCreateSocialMediaProcedure is the fully-qualified name of the
	// SocialMediaService's CreateSocialMedia RPC.
	SocialMediaServiceCreateSocialMediaProcedure = "/social_media.v1.SocialMediaService/CreateSocialMedia"
	// SocialMediaServiceUpdateSocialMediaProcedure is the fully-qualified name of the
	// SocialMediaService's UpdateSocialMedia RPC.
	SocialMediaServiceUpdateSocialMediaProcedure = "/social_media.v1.SocialMediaService/UpdateSocialMedia"
)

// SocialMediaServiceClient is a client for the social_media.v1.SocialMediaService service.
type SocialMediaServiceClient interface {
	CreateSocialMedia(context.Context, *connect.Request[v1.CreateSocialMediaRequest]) (*connect.Response[v1.CreateSocialMediaResponse], error)
	UpdateSocialMedia(context.Context, *connect.Request[v1.UpdateSocialMediaRequest]) (*connect.Response[v1.UpdateSocialMediaResponse], error)
}

// NewSocialMediaServiceClient constructs a client for the social_media.v1.SocialMediaService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSocialMediaServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SocialMediaServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &socialMediaServiceClient{
		createSocialMedia: connect.NewClient[v1.CreateSocialMediaRequest, v1.CreateSocialMediaResponse](
			httpClient,
			baseURL+SocialMediaServiceCreateSocialMediaProcedure,
			opts...,
		),
		updateSocialMedia: connect.NewClient[v1.UpdateSocialMediaRequest, v1.UpdateSocialMediaResponse](
			httpClient,
			baseURL+SocialMediaServiceUpdateSocialMediaProcedure,
			opts...,
		),
	}
}

// socialMediaServiceClient implements SocialMediaServiceClient.
type socialMediaServiceClient struct {
	createSocialMedia *connect.Client[v1.CreateSocialMediaRequest, v1.CreateSocialMediaResponse]
	updateSocialMedia *connect.Client[v1.UpdateSocialMediaRequest, v1.UpdateSocialMediaResponse]
}

// CreateSocialMedia calls social_media.v1.SocialMediaService.CreateSocialMedia.
func (c *socialMediaServiceClient) CreateSocialMedia(ctx context.Context, req *connect.Request[v1.CreateSocialMediaRequest]) (*connect.Response[v1.CreateSocialMediaResponse], error) {
	return c.createSocialMedia.CallUnary(ctx, req)
}

// UpdateSocialMedia calls social_media.v1.SocialMediaService.UpdateSocialMedia.
func (c *socialMediaServiceClient) UpdateSocialMedia(ctx context.Context, req *connect.Request[v1.UpdateSocialMediaRequest]) (*connect.Response[v1.UpdateSocialMediaResponse], error) {
	return c.updateSocialMedia.CallUnary(ctx, req)
}

// SocialMediaServiceHandler is an implementation of the social_media.v1.SocialMediaService service.
type SocialMediaServiceHandler interface {
	CreateSocialMedia(context.Context, *connect.Request[v1.CreateSocialMediaRequest]) (*connect.Response[v1.CreateSocialMediaResponse], error)
	UpdateSocialMedia(context.Context, *connect.Request[v1.UpdateSocialMediaRequest]) (*connect.Response[v1.UpdateSocialMediaResponse], error)
}

// NewSocialMediaServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSocialMediaServiceHandler(svc SocialMediaServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	socialMediaServiceCreateSocialMediaHandler := connect.NewUnaryHandler(
		SocialMediaServiceCreateSocialMediaProcedure,
		svc.CreateSocialMedia,
		opts...,
	)
	socialMediaServiceUpdateSocialMediaHandler := connect.NewUnaryHandler(
		SocialMediaServiceUpdateSocialMediaProcedure,
		svc.UpdateSocialMedia,
		opts...,
	)
	return "/social_media.v1.SocialMediaService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SocialMediaServiceCreateSocialMediaProcedure:
			socialMediaServiceCreateSocialMediaHandler.ServeHTTP(w, r)
		case SocialMediaServiceUpdateSocialMediaProcedure:
			socialMediaServiceUpdateSocialMediaHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSocialMediaServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSocialMediaServiceHandler struct{}

func (UnimplementedSocialMediaServiceHandler) CreateSocialMedia(context.Context, *connect.Request[v1.CreateSocialMediaRequest]) (*connect.Response[v1.CreateSocialMediaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("social_media.v1.SocialMediaService.CreateSocialMedia is not implemented"))
}

func (UnimplementedSocialMediaServiceHandler) UpdateSocialMedia(context.Context, *connect.Request[v1.UpdateSocialMediaRequest]) (*connect.Response[v1.UpdateSocialMediaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("social_media.v1.SocialMediaService.UpdateSocialMedia is not implemented"))
}
