syntax = "proto3";

package company.v1;

import "address/v1/address.proto";
import "phone/v1/phone.proto";
import "email/v1/email.proto";
import "social_media/v1/social_media.proto";

option go_package = "github.com/paladignus/actajus/proto/company/v1;companyv1";

service CompanyService {
  rpc CreateCompany(CreateCompanyRequest) returns (CreateCompanyResponse);
  rpc ListCompanies(ListCompaniesRequest) returns (ListCompaniesResponse);
  rpc UpdateCompany(UpdateCompanyRequest) returns (UpdateCompanyResponse);
  rpc DeleteCompany(DeleteCompanyRequest) returns (DeleteCompanyResponse);
}

message CreateCompanyRequest {
  string name = 1;
  string trade_name = 2;
  string cnpj = 3;
  address.v1.CreateAddressRequest address = 4;
  phone.v1.CreatePhoneRequest phone = 5;
  email.v1.CreateEmailRequest email = 6;
  repeated social_media.v1.CreateSocialMediaRequest social_media = 7;
}

message CreateCompanyResponse {
  int64 id = 1;
}

message ListCompaniesRequest {
  string after = 1;
  string before = 2;
  int64 limit = 3;
}

message ListCompaniesResponse {
  repeated company.v1.ListCompaniesResponse companies = 1;
}

message UpdateCompanyRequest {
  int64 id = 1;
  string name = 2;
  string trade_name = 3;
  string cnpj = 4;
  address.v1.UpdateAddressRequest address = 5;
  phone.v1.UpdatePhoneRequest phone = 6;
  email.v1.UpdateEmailRequest email = 7;
  repeated social_media.v1.UpdateSocialMediaRequest social_media = 8;
}

message UpdateCompanyResponse {
  int64 id = 1;
}

message DeleteCompanyRequest {
  int64 id = 1;
}

message DeleteCompanyResponse {}
