// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: identity/v1/rbac_admin.proto

package identityv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/paladignus/actajus/proto/identity/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// RbacAdminServiceName is the fully-qualified name of the RbacAdminService service.
	RbacAdminServiceName = "identity.v1.RbacAdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RbacAdminServiceAssignRoleToUserProcedure is the fully-qualified name of the RbacAdminService's
	// AssignRoleToUser RPC.
	RbacAdminServiceAssignRoleToUserProcedure = "/identity.v1.RbacAdminService/AssignRoleToUser"
	// RbacAdminServiceRemoveRoleFromUserProcedure is the fully-qualified name of the RbacAdminService's
	// RemoveRoleFromUser RPC.
	RbacAdminServiceRemoveRoleFromUserProcedure = "/identity.v1.RbacAdminService/RemoveRoleFromUser"
	// RbacAdminServiceGrantPermissionToRoleProcedure is the fully-qualified name of the
	// RbacAdminService's GrantPermissionToRole RPC.
	RbacAdminServiceGrantPermissionToRoleProcedure = "/identity.v1.RbacAdminService/GrantPermissionToRole"
	// RbacAdminServiceRevokePermissionFromRoleProcedure is the fully-qualified name of the
	// RbacAdminService's RevokePermissionFromRole RPC.
	RbacAdminServiceRevokePermissionFromRoleProcedure = "/identity.v1.RbacAdminService/RevokePermissionFromRole"
)

// RbacAdminServiceClient is a client for the identity.v1.RbacAdminService service.
type RbacAdminServiceClient interface {
	AssignRoleToUser(context.Context, *connect.Request[v1.AssignRoleToUserRequest]) (*connect.Response[v1.AssignRoleToUserResponse], error)
	RemoveRoleFromUser(context.Context, *connect.Request[v1.RemoveRoleFromUserRequest]) (*connect.Response[v1.RemoveRoleFromUserResponse], error)
	GrantPermissionToRole(context.Context, *connect.Request[v1.GrantPermissionToRoleRequest]) (*connect.Response[v1.GrantPermissionToRoleResponse], error)
	RevokePermissionFromRole(context.Context, *connect.Request[v1.RevokePermissionFromRoleRequest]) (*connect.Response[v1.RevokePermissionFromRoleResponse], error)
}

// NewRbacAdminServiceClient constructs a client for the identity.v1.RbacAdminService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRbacAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RbacAdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &rbacAdminServiceClient{
		assignRoleToUser: connect.NewClient[v1.AssignRoleToUserRequest, v1.AssignRoleToUserResponse](
			httpClient,
			baseURL+RbacAdminServiceAssignRoleToUserProcedure,
			opts...,
		),
		removeRoleFromUser: connect.NewClient[v1.RemoveRoleFromUserRequest, v1.RemoveRoleFromUserResponse](
			httpClient,
			baseURL+RbacAdminServiceRemoveRoleFromUserProcedure,
			opts...,
		),
		grantPermissionToRole: connect.NewClient[v1.GrantPermissionToRoleRequest, v1.GrantPermissionToRoleResponse](
			httpClient,
			baseURL+RbacAdminServiceGrantPermissionToRoleProcedure,
			opts...,
		),
		revokePermissionFromRole: connect.NewClient[v1.RevokePermissionFromRoleRequest, v1.RevokePermissionFromRoleResponse](
			httpClient,
			baseURL+RbacAdminServiceRevokePermissionFromRoleProcedure,
			opts...,
		),
	}
}

// rbacAdminServiceClient implements RbacAdminServiceClient.
type rbacAdminServiceClient struct {
	assignRoleToUser         *connect.Client[v1.AssignRoleToUserRequest, v1.AssignRoleToUserResponse]
	removeRoleFromUser       *connect.Client[v1.RemoveRoleFromUserRequest, v1.RemoveRoleFromUserResponse]
	grantPermissionToRole    *connect.Client[v1.GrantPermissionToRoleRequest, v1.GrantPermissionToRoleResponse]
	revokePermissionFromRole *connect.Client[v1.RevokePermissionFromRoleRequest, v1.RevokePermissionFromRoleResponse]
}

// AssignRoleToUser calls identity.v1.RbacAdminService.AssignRoleToUser.
func (c *rbacAdminServiceClient) AssignRoleToUser(ctx context.Context, req *connect.Request[v1.AssignRoleToUserRequest]) (*connect.Response[v1.AssignRoleToUserResponse], error) {
	return c.assignRoleToUser.CallUnary(ctx, req)
}

// RemoveRoleFromUser calls identity.v1.RbacAdminService.RemoveRoleFromUser.
func (c *rbacAdminServiceClient) RemoveRoleFromUser(ctx context.Context, req *connect.Request[v1.RemoveRoleFromUserRequest]) (*connect.Response[v1.RemoveRoleFromUserResponse], error) {
	return c.removeRoleFromUser.CallUnary(ctx, req)
}

// GrantPermissionToRole calls identity.v1.RbacAdminService.GrantPermissionToRole.
func (c *rbacAdminServiceClient) GrantPermissionToRole(ctx context.Context, req *connect.Request[v1.GrantPermissionToRoleRequest]) (*connect.Response[v1.GrantPermissionToRoleResponse], error) {
	return c.grantPermissionToRole.CallUnary(ctx, req)
}

// RevokePermissionFromRole calls identity.v1.RbacAdminService.RevokePermissionFromRole.
func (c *rbacAdminServiceClient) RevokePermissionFromRole(ctx context.Context, req *connect.Request[v1.RevokePermissionFromRoleRequest]) (*connect.Response[v1.RevokePermissionFromRoleResponse], error) {
	return c.revokePermissionFromRole.CallUnary(ctx, req)
}

// RbacAdminServiceHandler is an implementation of the identity.v1.RbacAdminService service.
type RbacAdminServiceHandler interface {
	AssignRoleToUser(context.Context, *connect.Request[v1.AssignRoleToUserRequest]) (*connect.Response[v1.AssignRoleToUserResponse], error)
	RemoveRoleFromUser(context.Context, *connect.Request[v1.RemoveRoleFromUserRequest]) (*connect.Response[v1.RemoveRoleFromUserResponse], error)
	GrantPermissionToRole(context.Context, *connect.Request[v1.GrantPermissionToRoleRequest]) (*connect.Response[v1.GrantPermissionToRoleResponse], error)
	RevokePermissionFromRole(context.Context, *connect.Request[v1.RevokePermissionFromRoleRequest]) (*connect.Response[v1.RevokePermissionFromRoleResponse], error)
}

// NewRbacAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRbacAdminServiceHandler(svc RbacAdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	rbacAdminServiceAssignRoleToUserHandler := connect.NewUnaryHandler(
		RbacAdminServiceAssignRoleToUserProcedure,
		svc.AssignRoleToUser,
		opts...,
	)
	rbacAdminServiceRemoveRoleFromUserHandler := connect.NewUnaryHandler(
		RbacAdminServiceRemoveRoleFromUserProcedure,
		svc.RemoveRoleFromUser,
		opts...,
	)
	rbacAdminServiceGrantPermissionToRoleHandler := connect.NewUnaryHandler(
		RbacAdminServiceGrantPermissionToRoleProcedure,
		svc.GrantPermissionToRole,
		opts...,
	)
	rbacAdminServiceRevokePermissionFromRoleHandler := connect.NewUnaryHandler(
		RbacAdminServiceRevokePermissionFromRoleProcedure,
		svc.RevokePermissionFromRole,
		opts...,
	)
	return "/identity.v1.RbacAdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RbacAdminServiceAssignRoleToUserProcedure:
			rbacAdminServiceAssignRoleToUserHandler.ServeHTTP(w, r)
		case RbacAdminServiceRemoveRoleFromUserProcedure:
			rbacAdminServiceRemoveRoleFromUserHandler.ServeHTTP(w, r)
		case RbacAdminServiceGrantPermissionToRoleProcedure:
			rbacAdminServiceGrantPermissionToRoleHandler.ServeHTTP(w, r)
		case RbacAdminServiceRevokePermissionFromRoleProcedure:
			rbacAdminServiceRevokePermissionFromRoleHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRbacAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRbacAdminServiceHandler struct{}

func (UnimplementedRbacAdminServiceHandler) AssignRoleToUser(context.Context, *connect.Request[v1.AssignRoleToUserRequest]) (*connect.Response[v1.AssignRoleToUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.v1.RbacAdminService.AssignRoleToUser is not implemented"))
}

func (UnimplementedRbacAdminServiceHandler) RemoveRoleFromUser(context.Context, *connect.Request[v1.RemoveRoleFromUserRequest]) (*connect.Response[v1.RemoveRoleFromUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.v1.RbacAdminService.RemoveRoleFromUser is not implemented"))
}

func (UnimplementedRbacAdminServiceHandler) GrantPermissionToRole(context.Context, *connect.Request[v1.GrantPermissionToRoleRequest]) (*connect.Response[v1.GrantPermissionToRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.v1.RbacAdminService.GrantPermissionToRole is not implemented"))
}

func (UnimplementedRbacAdminServiceHandler) RevokePermissionFromRole(context.Context, *connect.Request[v1.RevokePermissionFromRoleRequest]) (*connect.Response[v1.RevokePermissionFromRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.v1.RbacAdminService.RevokePermissionFromRole is not implemented"))
}
