// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: company/v1/company.proto

package companyv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/paladignus/actajus/proto/company/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// CompanyServiceName is the fully-qualified name of the CompanyService service.
	CompanyServiceName = "company.v1.CompanyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CompanyServiceCreateCompanyProcedure is the fully-qualified name of the CompanyService's
	// CreateCompany RPC.
	CompanyServiceCreateCompanyProcedure = "/company.v1.CompanyService/CreateCompany"
	// CompanyServiceListCompaniesProcedure is the fully-qualified name of the CompanyService's
	// ListCompanies RPC.
	CompanyServiceListCompaniesProcedure = "/company.v1.CompanyService/ListCompanies"
	// CompanyServiceUpdateCompanyProcedure is the fully-qualified name of the CompanyService's
	// UpdateCompany RPC.
	CompanyServiceUpdateCompanyProcedure = "/company.v1.CompanyService/UpdateCompany"
	// CompanyServiceDeleteCompanyProcedure is the fully-qualified name of the CompanyService's
	// DeleteCompany RPC.
	CompanyServiceDeleteCompanyProcedure = "/company.v1.CompanyService/DeleteCompany"
)

// CompanyServiceClient is a client for the company.v1.CompanyService service.
type CompanyServiceClient interface {
	CreateCompany(context.Context, *connect.Request[v1.CreateCompanyRequest]) (*connect.Response[v1.CreateCompanyResponse], error)
	ListCompanies(context.Context, *connect.Request[v1.ListCompaniesRequest]) (*connect.Response[v1.ListCompaniesResponse], error)
	UpdateCompany(context.Context, *connect.Request[v1.UpdateCompanyRequest]) (*connect.Response[v1.UpdateCompanyResponse], error)
	DeleteCompany(context.Context, *connect.Request[v1.DeleteCompanyRequest]) (*connect.Response[v1.DeleteCompanyResponse], error)
}

// NewCompanyServiceClient constructs a client for the company.v1.CompanyService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCompanyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CompanyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &companyServiceClient{
		createCompany: connect.NewClient[v1.CreateCompanyRequest, v1.CreateCompanyResponse](
			httpClient,
			baseURL+CompanyServiceCreateCompanyProcedure,
			opts...,
		),
		listCompanies: connect.NewClient[v1.ListCompaniesRequest, v1.ListCompaniesResponse](
			httpClient,
			baseURL+CompanyServiceListCompaniesProcedure,
			opts...,
		),
		updateCompany: connect.NewClient[v1.UpdateCompanyRequest, v1.UpdateCompanyResponse](
			httpClient,
			baseURL+CompanyServiceUpdateCompanyProcedure,
			opts...,
		),
		deleteCompany: connect.NewClient[v1.DeleteCompanyRequest, v1.DeleteCompanyResponse](
			httpClient,
			baseURL+CompanyServiceDeleteCompanyProcedure,
			opts...,
		),
	}
}

// companyServiceClient implements CompanyServiceClient.
type companyServiceClient struct {
	createCompany *connect.Client[v1.CreateCompanyRequest, v1.CreateCompanyResponse]
	listCompanies *connect.Client[v1.ListCompaniesRequest, v1.ListCompaniesResponse]
	updateCompany *connect.Client[v1.UpdateCompanyRequest, v1.UpdateCompanyResponse]
	deleteCompany *connect.Client[v1.DeleteCompanyRequest, v1.DeleteCompanyResponse]
}

// CreateCompany calls company.v1.CompanyService.CreateCompany.
func (c *companyServiceClient) CreateCompany(ctx context.Context, req *connect.Request[v1.CreateCompanyRequest]) (*connect.Response[v1.CreateCompanyResponse], error) {
	return c.createCompany.CallUnary(ctx, req)
}

// ListCompanies calls company.v1.CompanyService.ListCompanies.
func (c *companyServiceClient) ListCompanies(ctx context.Context, req *connect.Request[v1.ListCompaniesRequest]) (*connect.Response[v1.ListCompaniesResponse], error) {
	return c.listCompanies.CallUnary(ctx, req)
}

// UpdateCompany calls company.v1.CompanyService.UpdateCompany.
func (c *companyServiceClient) UpdateCompany(ctx context.Context, req *connect.Request[v1.UpdateCompanyRequest]) (*connect.Response[v1.UpdateCompanyResponse], error) {
	return c.updateCompany.CallUnary(ctx, req)
}

// DeleteCompany calls company.v1.CompanyService.DeleteCompany.
func (c *companyServiceClient) DeleteCompany(ctx context.Context, req *connect.Request[v1.DeleteCompanyRequest]) (*connect.Response[v1.DeleteCompanyResponse], error) {
	return c.deleteCompany.CallUnary(ctx, req)
}

// CompanyServiceHandler is an implementation of the company.v1.CompanyService service.
type CompanyServiceHandler interface {
	CreateCompany(context.Context, *connect.Request[v1.CreateCompanyRequest]) (*connect.Response[v1.CreateCompanyResponse], error)
	ListCompanies(context.Context, *connect.Request[v1.ListCompaniesRequest]) (*connect.Response[v1.ListCompaniesResponse], error)
	UpdateCompany(context.Context, *connect.Request[v1.UpdateCompanyRequest]) (*connect.Response[v1.UpdateCompanyResponse], error)
	DeleteCompany(context.Context, *connect.Request[v1.DeleteCompanyRequest]) (*connect.Response[v1.DeleteCompanyResponse], error)
}

// NewCompanyServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCompanyServiceHandler(svc CompanyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	companyServiceCreateCompanyHandler := connect.NewUnaryHandler(
		CompanyServiceCreateCompanyProcedure,
		svc.CreateCompany,
		opts...,
	)
	companyServiceListCompaniesHandler := connect.NewUnaryHandler(
		CompanyServiceListCompaniesProcedure,
		svc.ListCompanies,
		opts...,
	)
	companyServiceUpdateCompanyHandler := connect.NewUnaryHandler(
		CompanyServiceUpdateCompanyProcedure,
		svc.UpdateCompany,
		opts...,
	)
	companyServiceDeleteCompanyHandler := connect.NewUnaryHandler(
		CompanyServiceDeleteCompanyProcedure,
		svc.DeleteCompany,
		opts...,
	)
	return "/company.v1.CompanyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CompanyServiceCreateCompanyProcedure:
			companyServiceCreateCompanyHandler.ServeHTTP(w, r)
		case CompanyServiceListCompaniesProcedure:
			companyServiceListCompaniesHandler.ServeHTTP(w, r)
		case CompanyServiceUpdateCompanyProcedure:
			companyServiceUpdateCompanyHandler.ServeHTTP(w, r)
		case CompanyServiceDeleteCompanyProcedure:
			companyServiceDeleteCompanyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCompanyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCompanyServiceHandler struct{}

func (UnimplementedCompanyServiceHandler) CreateCompany(context.Context, *connect.Request[v1.CreateCompanyRequest]) (*connect.Response[v1.CreateCompanyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("company.v1.CompanyService.CreateCompany is not implemented"))
}

func (UnimplementedCompanyServiceHandler) ListCompanies(context.Context, *connect.Request[v1.ListCompaniesRequest]) (*connect.Response[v1.ListCompaniesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("company.v1.CompanyService.ListCompanies is not implemented"))
}

func (UnimplementedCompanyServiceHandler) UpdateCompany(context.Context, *connect.Request[v1.UpdateCompanyRequest]) (*connect.Response[v1.UpdateCompanyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("company.v1.CompanyService.UpdateCompany is not implemented"))
}

func (UnimplementedCompanyServiceHandler) DeleteCompany(context.Context, *connect.Request[v1.DeleteCompanyRequest]) (*connect.Response[v1.DeleteCompanyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("company.v1.CompanyService.DeleteCompany is not implemented"))
}
